### ISSUE TITLE
hyper_filename / hyper_file_name typo?

### ISSUE THREAD

**Issue by skyth540** [guilhermenoronha/parquet-to-hyper#14]
In the documentation, it says:

```
hyper_filename = 'path/to/your/db.hyper'            # Path to save hyper file with filename
rows = hf.create_hyper_file(hyper_file_name)
print(f'Hyper created with {rows} rows.')
```

is hyper_filename and hyper_file_name supposed to be the same thing?

**Comment by guilhermenoronha** [comment]
Hi. It should be the same name. For sure, it is a type. I'm going to fix the doc right now. Thanks for warning.
